import Base: (==), (!=), (<=), (<), (>=), (>), isless, isequal

@inline (==)(x::Double{T,E}, y::T) where {T<:SysFloat, E<:Emphasis} = iszero(lo(x)) && (hi(x) === y)
@inline (==)(x::T, y::Double{T,E}) where {T<:SysFloat, E<:Emphasis} = iszero(lo(y)) && (hi(y) === x)
@inline (!=)(x::Double{T,E}, y::T) where {T<:SysFloat, E<:Emphasis} = !iszero(lo(x)) || (hi(x) !== y)
@inline (!=)(x::T, y::Double{T,E}) where {T<:SysFloat, E<:Emphasis} = !iszero(lo(y)) || (hi(y) !== x)
@inline (<)(x::Double{T,E}, y::T) where {T<:SysFloat, E<:Emphasis} = (hi(x) < y) || ((hi(x) == y) && signbit(lo(x)))
@inline (<)(x::T, y::Double{T,E}) where {T<:SysFloat, E<:Emphasis} = (x < hi(y)) || ((x == hi(y)) && !signbit(lo(y)))
@inline (>)(x::Double{T,E}, y::T) where {T<:SysFloat, E<:Emphasis} = (hi(x) > y) || ((hi(x) == y) && (lo(x) < zero(T)))
@inline (>)(x::T, y::Double{T,E}) where {T<:SysFloat, E<:Emphasis} = (x > hi(y)) || ((x == hi(y)) && signbit(lo(y)))
@inline (<=)(x::Double{T,E}, y::T) where {T<:SysFloat, E<:Emphasis} = (hi(x) < y) || ((hi(x) == y) && (lo(x) <= zero(T)))
@inline (<=)(x::T, y::Double{T,E}) where {T<:SysFloat, E<:Emphasis} = (x < hi(y)) || ((x == hi(y)) && (lo(y) >= zero(T)))
@inline (>=)(x::Double{T,E}, y::T) where {T<:SysFloat, E<:Emphasis} = (hi(x) > y) || ((hi(x) == y) && (lo(x) <= zero(T)))
@inline (>=)(x::T, y::Double{T,E}) where {T<:SysFloat, E<:Emphasis} = (x > hi(y)) || ((x == hi(y)) && (lo(y) >= zero(T)))

@inline isequal(x::Double{T,E}, y::T) where {T<:SysFloat, E<:Emphasis} = (x == y)
@inline isequal(x::T, y::Double{T,E}) where {T<:SysFloat, E<:Emphasis} = (x == y)
@inline isless(x::Double{T,E}, y::T) where {T<:SysFloat, E<:Emphasis} = (x < y)
@inline isless(x::T, y::Double{T,E}) where {T<:SysFloat, E<:Emphasis} = (x < y)

@inline (==)(x::Double{T,E}, y::Double{T,E}) where {T<:SysFloat,E<:Emphasis} = (lo(x) === lo(y)) && (hi(x) === hi(y))
@inline (!=)(x::Double{T,E}, y::Double{T,E}) where {T<:SysFloat,E<:Emphasis} = (lo(x) !== lo(y)) || (hi(x) !== hi(y))
@inline (<)(x::Double{T,E}, y::Double{T,E}) where {T<:SysFloat,E<:Emphasis} = (hi(x) < hi(y)) || (hi(x) === hi(y) && lo(x) < lo(y))
@inline (>)(x::Double{T,E}, y::Double{T,E}) where {T<:SysFloat,E<:Emphasis} = (hi(x) > hi(y)) || (hi(x) === hi(y) && lo(x) > lo(y))
@inline (<=)(x::Double{T,E}, y::Double{T,E}) where {T<:SysFloat,E<:Emphasis} = (hi(x) < hi(y)) || (hi(x) === hi(y) && lo(x) <= lo(y))
@inline (>=)(x::Double{T,E}, y::Double{T,E}) where {T<:SysFloat,E<:Emphasis} = (hi(x) > hi(y)) || (hi(x) === hi(y) && lo(x) >= lo(y))

@inline isequal(x::Double{T,E}, y::Double{T,E}) where {T<:SysFloat,E<:Emphasis} = (x == y)
@inline isless(x::Double{T,E}, y::Double{T,E}) where {T<:SysFloat,E<:Emphasis} = (x < y)

@inline (==)(x::Double{T,E1}, y::Double{T,E2}) where {T<:SysFloat,E1<:Emphasis,E2<:Emphasis} = (==)(promote(x, y)...)
@inline (!=)(x::Double{T,E1}, y::Double{T,E2}) where {T<:SysFloat,E1<:Emphasis,E2<:Emphasis} = (!=)(promote(x, y)...)
@inline (<)(x::Double{T,E1}, y::Double{T,E2}) where {T<:SysFloat,E1<:Emphasis,E2<:Emphasis} = (<)(promote(x, y)...)
@inline (>)(x::Double{T,E1}, y::Double{T,E2}) where {T<:SysFloat,E1<:Emphasis,E2<:Emphasis} = (>)(promote(x, y)...)
@inline (<=)(x::Double{T,E1}, y::Double{T,E2}) where {T<:SysFloat,E1<:Emphasis,E2<:Emphasis} = (<=)(promote(x, y)...)
@inline (>=)(x::Double{T,E1}, y::Double{T,E2}) where {T<:SysFloat,E1<:Emphasis,E2<:Emphasis} = (>=)(promote(x, y)...)
@inline isequal(x::Double{T,E1}, y::Double{T,E2}) where {T<:SysFloat,E1<:Emphasis,E2<:Emphasis} = isequal(promote(x, y)...)
@inline isless(x::Double{T,E1}, y::Double{T,E2}) where {T<:SysFloat,E1<:Emphasis,E2<:Emphasis} = isless(promote(x, y)...)

@inline (==)(x::Double{T1,E}, y::Double{T2,E}) where {T1<:SysFloat,T2<:SysFloat,E<:Emphasis} = (==)(promote(x, y)...)
@inline (!=)(x::Double{T1,E}, y::Double{T2,E}) where {T1<:SysFloat,T2<:SysFloat,E<:Emphasis} = (!=)(promote(x, y)...)
@inline (<)(x::Double{T1,E}, y::Double{T2,E}) where {T1<:SysFloat,T2<:SysFloat,E<:Emphasis} = (<)(promote(x, y)...)
@inline (>)(x::Double{T1,E}, y::Double{T2,E}) where {T1<:SysFloat,T2<:SysFloat,E<:Emphasis} = (>)(promote(x, y)...)
@inline (<=)(x::Double{T1,E}, y::Double{T2,E}) where {T1<:SysFloat,T2<:SysFloat,E<:Emphasis} = (<=)(promote(x, y)...)
@inline (>=)(x::Double{T1,E}, y::Double{T2,E}) where {T1<:SysFloat,T2<:SysFloat,E<:Emphasis} = (>=)(promote(x, y)...)
@inline isequal(x::Double{T1,E}, y::Double{T2,E}) where {T1<:SysFloat,T2<:SysFloat,E<:Emphasis} = isequal(promote(x, y)...)
@inline isless(x::Double{T1,E}, y::Double{T2,E}) where {T1<:SysFloat,T2<:SysFloat,E<:Emphasis} = isless(promote(x, y)...)

@inline (==)(x::Double{T1,E1}, y::Double{T2,E2}) where {T1<:SysFloat,T2<:SysFloat,E1<:Emphasis,E2<:Emphasis} = (==)(Double(EMPHASIS, hi(x), lo(x)), Double(EMPHASIS, hi(y), lo(y)))
@inline (!=)(x::Double{T1,E1}, y::Double{T2,E2}) where {T1<:SysFloat,T2<:SysFloat,E1<:Emphasis,E2<:Emphasis} = (!=)(Double(EMPHASIS, hi(x), lo(x)), Double(EMPHASIS, hi(y), lo(y)))
@inline (<)(x::Double{T1,E1}, y::Double{T2,E2}) where {T1<:SysFloat,T2<:SysFloat,E1<:Emphasis,E2<:Emphasis} = (<)(Double(EMPHASIS, hi(x), lo(x)), Double(EMPHASIS, hi(y), lo(y)))
@inline (>)(x::Double{T1,E1}, y::Double{T2,E2}) where {T1<:SysFloat,T2<:SysFloat,E1<:Emphasis,E2<:Emphasis} = (>)(Double(EMPHASIS, hi(x), lo(x)), Double(EMPHASIS, hi(y), lo(y)))
@inline (<=)(x::Double{T1,E1}, y::Double{T2,E2}) where {T1<:SysFloat,T2<:SysFloat,E1<:Emphasis,E2<:Emphasis} = (<=)(Double(EMPHASIS, hi(x), lo(x)), Double(EMPHASIS, hi(y), lo(y)))
@inline (>=)(x::Double{T1,E1}, y::Double{T2,E2}) where {T1<:SysFloat,T2<:SysFloat,E1<:Emphasis,E2<:Emphasis} = (>=)(Double(EMPHASIS, hi(x), lo(x)), Double(EMPHASIS, hi(y), lo(y)))
@inline isequal(x::Double{T1,E1}, y::Double{T2,E2}) where {T1<:SysFloat,T2<:SysFloat,E1<:Emphasis,E2<:Emphasis} = isequal(Double(EMPHASIS, hi(x), lo(x)), Double(EMPHASIS, hi(y), lo(y)))
@inline isless(x::Double{T1,E1}, y::Double{T2,E2}) where {T1<:SysFloat,T2<:SysFloat,E1<:Emphasis,E2<:Emphasis} = isless(Double(EMPHASIS, hi(x), lo(x)), Double(EMPHASIS, hi(y), lo(y)))
